/*
  Warnings:

  - Added the required column `manufacturerNames` to the `UC16UFN001Setting` table without a default value. This is not possible if the table is not empty.
  - Added the required column `manufacturingTypes` to the `UC16UFN001Setting` table without a default value. This is not possible if the table is not empty.
  - Added the required column `modelNames` to the `UC16UFN001Setting` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE `UC16UFN001Setting` ADD COLUMN `aircraftWeightMax` DOUBLE NULL,
    ADD COLUMN `aircraftWeightMin` DOUBLE NULL,
    ADD COLUMN `flightAirspace150mAboveGround` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightAirspaceAirportSurroundings` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightAirspaceDID` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightAirspaceNone` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightAltitudeMax` INTEGER NULL,
    ADD COLUMN `flightAltitudeMin` INTEGER NULL,
    ADD COLUMN `flightMethodBeyondVisualLineOfSight` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightMethodDuringEvents` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightMethodNightOperations` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightMethodNone` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightMethodObjectDropping` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightMethodOverHazardousAreas` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightMethodWithin30m` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeAerialPhotography` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeAgricultureForestryAndFisheries` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeEnvironmentalResearch` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeEquipmentMaintenance` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeHobby` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeIncidentDisasterResponse` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeInfrastructureInspectionAndMaintenance` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeJournalism` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeMaterialManagement` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeNatureObservation` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeOtherForCommercial` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeOtherForNonCommercial` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeResearchAndDevelopment` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeSecurity` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeSurveying` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightPurposeTransportationDelivery` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `flightSpeedMax` INTEGER NULL,
    ADD COLUMN `flightSpeedMin` INTEGER NULL,
    ADD COLUMN `heightMax` DOUBLE NULL,
    ADD COLUMN `heightMin` DOUBLE NULL,
    ADD COLUMN `lengthMax` DOUBLE NULL,
    ADD COLUMN `lengthMin` DOUBLE NULL,
    ADD COLUMN `manufacturerNames` JSON NOT NULL,
    ADD COLUMN `manufacturingTypes` JSON NOT NULL,
    ADD COLUMN `maximumTakeoffWeightMax` DOUBLE NULL,
    ADD COLUMN `maximumTakeoffWeightMin` DOUBLE NULL,
    ADD COLUMN `modelNames` JSON NOT NULL,
    ADD COLUMN `personalLiabilityCoverageAmountMax` INTEGER NULL,
    ADD COLUMN `personalLiabilityCoverageAmountMin` INTEGER NULL,
    ADD COLUMN `propertyDamageCoverageAmountMax` INTEGER NULL,
    ADD COLUMN `propertyDamageCoverageAmountMin` INTEGER NULL,
    ADD COLUMN `requiredDurationMax` INTEGER NULL,
    ADD COLUMN `requiredDurationMin` INTEGER NULL,
    ADD COLUMN `wingspanMax` DOUBLE NULL,
    ADD COLUMN `wingspanMin` DOUBLE NULL;
