export const routes = {
	login: "/login",
	logout: "/logout",
	structureCallback: "/api/structure/callback",
	operator: "/operators",
	operatorDataStructure: "/operators/data-structure",
	operatorPreProcessing: "/operators/pre-processing",
	operatorTextMatching: "/operators/text-matching",
	operatorCrossTab: "/operators/cross-tab",
	operatorSpatialJoin: "/operators/spatial-join",
	operatorSpatialAggregation: "/operators/spatial-aggregation",
	asset: "/assets",
	content: "/contents",
	contentDetail: (contentId: string) => `/contents/${contentId}`,
	item: "/items",
	contentVisualize: "/contents-visualize",
	dataset: "/dataset",
	visualization: "/visualizations",
	template: "/templates",
	processingStatus: "/processing-status",
	chat: "/chat",
	chatStatus: "/chat-status",
	accountManagement: "/account-management",
	contentDetailApi: (contentId: string) => `/api/content/${contentId}`,
	preprocessCallback: "/api/preprocess/callback",
	textMatchingCallback: "/api/text-matching/callback",
	crossJoinCallback: "/api/cross-join/callback",
	spatialJoinCallback: "/api/spatial-join/callback",
	spatialAggregateCallback: "/api/spatial-aggregate/callback",
	chatCallback: "/api/chat/callback",
	contentDetailModel: (contentId: string) => `/model/${contentId}`,
};

export const defaultAuthorizedPage = routes.operator;
