-- DropForeignKey
ALTER TABLE `UC16UFN001ChartSetting` DROP FOREIGN KEY `UC16UFN001ChartSetting_filterId_fkey`;

-- DropForeignKey
ALTER TABLE `UC16UFN001Setting` DROP FOREIGN KEY `UC16UFN001Setting_filterId_fkey`;

-- AddForeignKey
ALTER TABLE `UC16UFN001Setting` ADD CONSTRAINT `UC16UFN001Setting_filterId_fkey` FOREIGN KEY (`filterId`) REFERENCES `UC16UFN001Filter`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `UC16UFN001ChartSetting` ADD CONSTRAINT `UC16UFN001ChartSetting_filterId_fkey` FOREIGN KEY (`filterId`) REFERENCES `UC16UFN001Filter`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
