-- AlterTable
ALTER TABLE `UC16UFN001Setting` ADD COLUMN `airportZone` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `didZone` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `mannedZone` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `redZone` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `yellowZone` BOOLEAN NOT NULL DEFAULT false;
