import {
	AssetsCommentsService,
	AssetsProjectService,
	AssetsService,
	CsvService,
	FieldsService,
	GeoJsonService,
	ItemsCommentsService,
	ItemsProjectService,
	ItemsService,
	JsonService,
	MetadataSchemaService,
	ModelsService,
	ProjectsService,
	SchemaService,
	SchemataService,
} from ".";

export const ApiClient = {
	AssetsCommentsService: AssetsCommentsService,
	AssetsProjectService: AssetsProjectService,
	AssetsService: AssetsService,
	CsvService: CsvService,
	FieldsService: FieldsService,
	GeoJsonService: GeoJsonService,
	ItemsCommentsService: ItemsCommentsService,
	ItemsProjectService: ItemsProjectService,
	ItemsService: ItemsService,
	JsonService: JsonService,
	MetadataSchemaService: MetadataSchemaService,
	ModelsService: ModelsService,
	ProjectsService: ProjectsService,
	SchemaService: SchemaService,
	SchemataService: SchemataService,
};
